
MARC = {

 t: {
   legend: 'Select a marc base (archetype)',
   options: [
    'Marc',
    'Marc Mid',
    'Marc Dark',
    'Marc Albino',
    'Marc Golden',
    'Mad Lad',
    'Zombie',
    'Ape',
    'Ape Golden',
    'Ape Pink',
    'Alien',
    'Alien Green',
    'Devil',
    'Orc',
    'Skeleton',
    'Bot'],
 },

 eyes: {
  legend: 'Select eyes (extras)',
  none: true,
  options: [
    'Blue Eyes',
    'Green Eyes',
  ],
 },

 face: {
  legend: 'Select face (extras)',
  none: true,
  options: [
    'Blue Eye Shadow',
    'Green Eye Shadow',
    'Purple Eye Shadow',
    'Clown Eyes Blue',
    'Clown Eyes Green',
    'Bagner',
    'Marc Tyson',
    'Tears',
  ],
 },

 beard: {
  legend: 'Select beard',
  none: true,
  options: [
    'Big Beard White',
    'Big Beard',
    'Chinstrap',
    'Front Beard',
    'Front Beard Dark',
    'Full Mustache',
    'Full Mustache Dark',
    'Goat',
    'Goat Dark',
    'Handlebar',
    'Luxurious Beard',
    'Mustache',
    'Mutton Chop',
    'Normal Beard',
    'Normal Beard Black',
    'Shadow Beard',
    'Soul Patch',
  ],
 },

 hair: {
  legend: 'Select hair',
  none: true,
  options: [
    'Blonde Bob',
    'Chad',
    'Clown Hair',
    'Crazy White Hair',
    'Crazy Hair',
    'Frumpy Hair',
    'Marc Three',
    'Purple Hair',
    'Stringy Hair',
    'Vampire Hair',
    'Wild Blonde Hair',
    'Wild Hair',
  ],
 },

 headwear: {
  legend: 'Select headwear',
  none: true,
  options: [
    'Bandana',
    'Beanie',
    'Bunny Ears',
    'Cap',
    'Skull Cap',
    'Cap Forward',
    'Police Cap',
    'Cowboy Hat',
    'Do Rag',
    'Fast Food',
    'Marcdonalds',
    'Fedora',
    'Headband',
    'Roaring Headband',
    'Hoodie',
    'Purple Hoodie',
    'Knitted Cap',
    'Laurels',
    'Shemagh',
    'Tassle Hat',
    'Tiarra',
    'Top Hat',
    'Uncle Sam',
    'Viking',
    'Welding Goggles',
  ],
 },

 eyewear: {
  legend: 'Select eyewear',
  none: true,
  options: [
    '3D Glasses',
    'Aviators',
    'Big Shades',
    'Classic Shades',
    'Deal With It',
    'Glasses',
    'Gold Glasses',
    'Horned-Rim Glasses',
    'Monocle',
    'Nerd Glasses',
    'Pink Shades',
    'Polarized',
    'Polarized White',
    'Regular Shades',
    'Small Shades',
    'VR Headset',
    'Eye Mask',
    'Eye Patch',
    'Lasers'],
 },

 mouth: {
  legend: 'Select mouth prop',
  none: true,
  options: [
    'Cigar',
    'Cigarette',
    'Hookah',
    'Pipe',
    'Vape',
    'Medical Mask',
    'Bubble Gum' ],
 },
}


